##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://triplingual.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /code4lib-workshop
# location of code, the full url to your github repository
source-code: https://github.com/triplingual/code4lib-workshop

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Trip's Special Collex Items
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A group of olio, miscellany, and this-n-that
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Description goes here"
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: New Haven;history;maps;photos
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Trip Kirkpatrick

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: psychiana_cbdemo_csv_urls
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Yale University Library"
organization-link: https://library.yale.edu/
organization-logo-banner: https://www.yale.edu/sites/all/themes/yale_blue/images/logo-print.png
organization-logo-nav: https://library.yale.edu/sites/default/files/files/FinalULWhite-1000px.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
